import Providers from '@/store/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import NextAuthProvider from '@/components/NextAuthProvider/NextAuthProvider'
import Toastify from '@/client/components/Toastify/Toastify'

export const dynamic = 'force-dynamic'
import 'swiper/css';


const roboto = Roboto({weight: ["400"], display: 'swap', preload: true, subsets: ['latin-ext']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <NextAuthProvider>
                    <Providers>
                        <Toastify/>
                        {children}
                    </Providers>
                </NextAuthProvider>
            </body>
        </html>
    )
}